- hosts: all
  become: yes
  tasks:
    - name: fail if OS is not CentOS 8.5
      fail:
        msg: "OS should be CentOS 8.5, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'

    - name: Add hostname and IP address to /etc/hosts file
  command: "sudo -- sh -c \"echo $(hostname -i) $(hostname) >> /etc/hosts\""

- name: Disable firewalld service
  command: "sudo systemctl disable firewalld"

- name: Disable SELinux enforcement
  command: "sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config"

- name: Remove swap entry from /etc/fstab
  command: "sudo sed -i '/swap/d' /etc/fstab"

- name: Configure modules for Containerd by adding them to /etc/modules-load.d/containerd.conf
  command: |
    sudo tee /etc/modules-load.d/containerd.conf << EOF
    overlay
    br_netfilter
    EOF

- name: Configure sysctl parameters for Kubernetes by adding them to /etc/sysctl.d/99-kubernetes-cri.conf
  command: |
    sudo tee /etc/sysctl.d/99-kubernetes-cri.conf << EOF
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF

- name: Stop firewalld service
  command: "sudo systemctl stop firewalld"

- name: Set SELinux to Permissive mode
  command: "sudo setenforce Permissive"

- name: Load kernel modules
  command: "sudo modprobe overlay && sudo modprobe br_netfilter"

- name: Apply sysctl changes
  command: "sudo sysctl --system"

- name: Install required packages
  command: "sudo yum install iproute-tc chrony -y"

- name: Install yum-utils for repository management
  command: "sudo yum install yum-utils -y"

- name: Add Docker repository
  command: "sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Update system packages
  command: "sudo yum update -y"

- name: Install containerd.io
  command: "sudo yum install containerd.io -y"

- name: Create directory for containerd configuration
  command: "sudo mkdir -p /etc/containerd"

- name: Generate default containerd configuration and save it to /etc/containerd/config.toml
  command: "sudo containerd config default | sudo tee /etc/containerd/config.toml"

- name: Enable systemd cgroup driver for containerd in the configuration file previously generated
  command: "sudo sed -i 's/SystemdCgroup \\= false/SystemdCgroup \\= true/g' /etc/containerd/config.toml"

- name: Restart and enable containerd service to avoid manual restart when rebooting
  command:
    - "sudo systemctl restart containerd"
    - "sudo systemctl enable containerd"

- name: Add Kubernetes repository to /etc/yum.repos.d/kubernetes.repo
  command: |
    sudo tee /etc/yum.repos.d/kubernetes.repo <<EOF
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOF

- name: Update system packages to enrich your package list with the previously added Kubernetes repository
  command: "sudo yum update -y"

- name: Install kubelet, kubeadm, and kubectl
  command: "sudo yum install kubelet kubeadm kubectl -y"

- name: Enable and start kubelet service
  command:
    - "sudo systemctl enable kubelet.service"
    - "sudo systemctl start kubelet.service"

- name: Install yum-plugin-versionlock for package version locking
  command: "sudo yum install yum-plugin-versionlock -y"

- name: Lock kubelet, kubeadm, and kubectl versions to prevent automatic updates and keep consistent version to avoid conflicts in the future
  command: "sudo yum versionlock kubelet kubeadm kubectl"
